-- Umbra Platform — Initial Schema
-- Run this once in: https://supabase.com/dashboard/project/nhnarrnelvruwowszkow/sql/new

-- ENUMS
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('platform_admin','org_owner','org_admin','team_member'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE membership_status AS ENUM ('active','invited','suspended','removed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE agent_type AS ENUM ('quote','intake','follow_up','buyer_search','match','alert'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE submission_status AS ENUM ('new','reviewing','quoted','accepted','declined','closed','archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE lead_status AS ENUM ('new','contacted','qualified','proposal','won','lost','archived'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE follow_up_status AS ENUM ('pending','sent','responded','skipped','failed'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE notification_type AS ENUM ('new_submission','lead_assigned','follow_up_due','ai_scored','team_invite','billing_alert'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- TABLES
CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), auth_id TEXT UNIQUE, email TEXT NOT NULL UNIQUE, full_name TEXT, avatar_url TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS organizations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, logo_url TEXT, brand_config JSONB DEFAULT '{}', plan_id TEXT, trial_ends_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS memberships (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), organization_id UUID REFERENCES organizations(id), role user_role NOT NULL DEFAULT 'team_member', status membership_status NOT NULL DEFAULT 'active', invited_by UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS agents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), name TEXT NOT NULL, slug TEXT NOT NULL, type agent_type NOT NULL DEFAULT 'quote', description TEXT, system_prompt TEXT, is_active BOOLEAN DEFAULT true, config JSONB DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS intake_forms (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), agent_id UUID REFERENCES agents(id), organization_id UUID REFERENCES organizations(id), version INTEGER DEFAULT 1, fields JSONB DEFAULT '[]', is_active BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS submissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), agent_id UUID REFERENCES agents(id), organization_id UUID REFERENCES organizations(id), form_id UUID REFERENCES intake_forms(id), submitter_name TEXT, submitter_email TEXT, submitter_phone TEXT, raw_data JSONB DEFAULT '{}', status submission_status NOT NULL DEFAULT 'new', ai_summary TEXT, ai_structured_data JSONB, ai_missing_fields JSONB, ai_suggested_next_steps JSONB, ai_quote_ready_score INTEGER, ai_processed_at TIMESTAMPTZ, source_url TEXT, ip_address TEXT, user_agent TEXT, assigned_to UUID REFERENCES users(id), created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS leads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), submission_id UUID REFERENCES submissions(id), organization_id UUID REFERENCES organizations(id), agent_id UUID REFERENCES agents(id), name TEXT, email TEXT, phone TEXT, status lead_status NOT NULL DEFAULT 'new', score INTEGER DEFAULT 0, estimated_value DECIMAL(12,2), assigned_to UUID REFERENCES users(id), tags TEXT[], last_contacted_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS pipeline_stages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), name TEXT NOT NULL, position INTEGER NOT NULL, color TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS notes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), lead_id UUID REFERENCES leads(id), submission_id UUID REFERENCES submissions(id), author_id UUID REFERENCES users(id), content TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS follow_ups (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), lead_id UUID REFERENCES leads(id), agent_id UUID REFERENCES agents(id), assigned_to UUID REFERENCES users(id), status follow_up_status NOT NULL DEFAULT 'pending', channel TEXT DEFAULT 'email', message TEXT, scheduled_for TIMESTAMPTZ, sent_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES users(id), organization_id UUID REFERENCES organizations(id), type notification_type NOT NULL, title TEXT NOT NULL, body TEXT, entity_type TEXT, entity_id UUID, read_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS analytics_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), agent_id UUID REFERENCES agents(id), user_id UUID REFERENCES users(id), event_name TEXT NOT NULL, entity_type TEXT, entity_id UUID, properties JSONB DEFAULT '{}', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), organization_id UUID REFERENCES organizations(id), stripe_subscription_id TEXT UNIQUE, stripe_customer_id TEXT, plan_id TEXT, status TEXT NOT NULL DEFAULT 'active', current_period_start TIMESTAMPTZ, current_period_end TIMESTAMPTZ, canceled_at TIMESTAMPTZ, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
